[package]
name = "bogo-renderer"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
image = "0.23.14"
rayon = "1.5"
hexasphere = "6"
